/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    AccessTokens: () => import('#controllers/auth/access_tokens_controller'),
    NewAccount: () => import('#controllers/auth/new_account_controller'),
    Profile: () => import('#controllers/auth/profile_controller'),
  },
}
