/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type AuthUsuarioTransformer from '#transformers/auth/usuario_transformer'

export namespace Data {
  export namespace Auth {
    export type Usuario = InferData<AuthUsuarioTransformer>
    export namespace Usuario {
      export type Variants = InferVariants<AuthUsuarioTransformer>
    }
  }
}
